### PR TITLE
STY clean out a few flake8 warnings

### PR DESCRIPTION
**Pull request by beckermr**
This PR cleans out a few flake8 errors.

### CODE REVIEW

**Comment by beckermr** [comment]
Ohhhhh the galsim test suite might have odd imports.

**Comment by beckermr** [comment]
@ismael-mendoza @EiffL What is the general turn around time on PRs, reviews, etc.?

I don't want to rush anyone but I am coding almost half my time on this project right now and so will be pushing a ton. Should I tag someone else? I don't want to burden anyone.

**Review by ismael-mendoza — APPROVED** [review]
Looks great, thanks @beckermr I think you can merge this PR.

**Comment by beckermr** [comment]
Can you add me as a collaborator on this repo? I do not have merge rights.

**Comment by ismael-mendoza** [comment]
> @ismael-mendoza @EiffL What is the general turn around time on PRs, reviews, etc.?
> 
> I don't want to rush anyone but I am coding almost half my time on this project right now and so will be pushing a ton. Should I tag someone else? I don't want to burden anyone.

Thanks @beckermr - usually we tend to take 1 or 2 days for a review but it can vary depending on availability (since we are a small team consiting of just @EiffL, @jecampagne, and myself). I should be available for a ~1 day turnaround for reviews in the coming days in case that's helpful. I'm taking a look at your other PRs right now.

**Comment by beckermr** [comment]
OK. No rush from my end at all. Just trying to be a good citizen. I can help review PRs here too.

**Comment by ismael-mendoza** [comment]
> Can you add me as a collaborator on this repo? I do not have merge rights.

Just added you

> OK. No rush from my end at all. Just trying to be a good citizen. I can help review PRs here too.

Sounds good and we would appreciate that, thank you!

**Pull request merged**
